version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: yolora-db
    environment:
      POSTGRES_DB: yolora
      POSTGRES_USER: yolora_user
      POSTGRES_PASSWORD: yolora_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
